/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_com_zh_uninstalllistener_MainActivity */

#ifndef _Included_test_com_zh_uninstalllistener_MainActivity
#define _Included_test_com_zh_uninstalllistener_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_com_zh_uninstalllistener_MainActivity
 * Method:    callC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_com_zh_uninstalllistener_MainActivity_callC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
